version: '3.7'
services:
  kibana:
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure
    image: docker.elastic.co/kibana/kibana:7.5.1
    ports:
      - 5601:5601
    environment:
      ELASTICSEARCH_URL: http://es01:9200
      ELASTICSEARCH_HOSTS: http://es01:9200
    networks:
      - frontend

networks:
  frontend:
    driver: overlay
    external: true
