version: '3.7'

services:
  logstash:
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure
    image: docker.elastic.co/logstash/logstash:7.5.1
    volumes:
      - ./logstash.conf:/usr/share/logstash/config/logstash.yml
      - ./logstash.pipeline:/usr/share/logstash/pipeline/logstash.conf
        #- ./html:/usr/share/nginx/html
    ports:
      - 5044:5044
      - 9600:9600
    networks:
      - frontend

networks:
  frontend:
    driver: overlay
    external: true
